spring.application.name=invoquill-api

spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dev-postgres-db:5432/invoquill-dev}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:jashawnrogers}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Disable Hibernate to allow Flyway to manage SQL
# 'validate': Hibernate checks table structure against entities at startup but changes NOTHING.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Logging
spring.output.ansi.enabled=ALWAYS
logging.level.root=warn
logging.level.org.springframework.web=debug
logging.level.org.hibernate=error