package com.jashawnbuilds.invoquill_api.shared.adapter.in.web.error;

import org.jspecify.annotations.Nullable;

import java.time.Instant;
import java.util.List;

/**
 * The {@code ApiErrorResponse} object is intended to be used for every error response the API sends.
 * The goal is to provide consistent error handling which makes for predictable responses to the client.
 * The {@code ApiErrorResponse} follows {@code RFC 9457}.
 * Each domain owns what can go wrong. The shared inbound REST adapter owns how those failures are
 * communicated over HTTP.
 *
 * @param status
 *        The HTTP status code generated by the origin server for this occurrence of the problem.
 * @param error
 *        A short, human-readable summary of the problem type.
 * @param code
 *        An API specific error code aiming to provide context of the error to the client.
 *        Ex: 409 Conflict -> EMAIL_ALREADY_EXISTS
 * @param message
 *        A human-readable explanation specific to this occurrence of the problem.
 * @param path
 *        A URI reference that identifies the specific occurrence of the problem.
 * @param timestamp
 *        Timestamp of when error occurred.
 * @param fieldErrors
 * @see FieldValidationError
 */
public record ApiErrorResponse(
        int status,
        String error,
        String code,
        String message,
        String path,
        Instant timestamp,
        @Nullable List<FieldValidationError> fieldErrors
) {
}
